//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionInfo
    {
        public int OptionId { get; set; }
        public int QuesionId { get; set; }
        public string OptionKey { get; set; }
        public string OptionValue { get; set; }
        public bool Deleted { get; set; }
        public string Remark { get; set; }
    }
}
