//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionInfo
    {
        public int QuestionId { get; set; }
        public int SurveyId { get; set; }
        public string QuestionTitle { get; set; }
        public int QuestionOptionsCount { get; set; }
        public int RequiredOptionsCount { get; set; }
        public Nullable<bool> IsOrientation { get; set; }
        public bool Deleted { get; set; }
        public string Remark { get; set; }
    }
}
